name: MsiZapEx Build
on:
  push:
  workflow_dispatch:
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2

      - run: nuget restore

      - name: Build solution
        run: msbuild MsiZapEx.sln -m -p:Configuration=Release

      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          files: build\bin\Release\MsiZapEx\
          dest: MsiZapEx.zip

      - name: Extract tag or branch name
        if: startsWith(github.ref, 'refs/tags/')
        id: tagName
        run: echo ::set-output name=tag::${GITHUB_REF_NAME#v}

      - name: Publish nuget packages to github repository
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          nuget.exe pack "MsiZapEx\MsiZapEx.nuspec" -Version "${{ steps.tagName.outputs.tag }}"
          dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push MsiZapEx.${{ steps.tagName.outputs.tag }}.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MsiZapEx.zip
          path: |
            MsiZapEx.zip
            ./*.nupkg

      - name: Publish (pre-)release
        uses: softprops/action-gh-release@v0.1.14
        with:
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
          files: MsiZapEx.zip
          generate_release_notes: true
          tag_name: Build_${{ github.run_number }}_${{ github.ref_type }}_${{ github.ref_name }}
